// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBrE4zIQt6lnUeADBwqainbFfkZPgUv2kk',
    appId: '1:6460870181:web:49334572538f3b16cdf9cc',
    messagingSenderId: '6460870181',
    projectId: 'cis-student-app',
    authDomain: 'cis-student-app.firebaseapp.com',
    storageBucket: 'cis-student-app.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyATY9aeiBKZ9rQaBLFjBB-YSz9OIB2kESA',
    appId: '1:6460870181:android:8eea2f6ffdaff0f0cdf9cc',
    messagingSenderId: '6460870181',
    projectId: 'cis-student-app',
    storageBucket: 'cis-student-app.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBZrn6vbnBXMbjIVJVxmQgR96cnEqhU28A',
    appId: '1:6460870181:ios:593eda0475e0e269cdf9cc',
    messagingSenderId: '6460870181',
    projectId: 'cis-student-app',
    storageBucket: 'cis-student-app.firebasestorage.app',
    iosBundleId: 'com.example.cisStudentApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBZrn6vbnBXMbjIVJVxmQgR96cnEqhU28A',
    appId: '1:6460870181:ios:593eda0475e0e269cdf9cc',
    messagingSenderId: '6460870181',
    projectId: 'cis-student-app',
    storageBucket: 'cis-student-app.firebasestorage.app',
    iosBundleId: 'com.example.cisStudentApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBrE4zIQt6lnUeADBwqainbFfkZPgUv2kk',
    appId: '1:6460870181:web:454cdee0fc751ac6cdf9cc',
    messagingSenderId: '6460870181',
    projectId: 'cis-student-app',
    authDomain: 'cis-student-app.firebaseapp.com',
    storageBucket: 'cis-student-app.firebasestorage.app',
  );
}
